### ISSUE TITLE
Should tab key be used to navigate between options, or should it immediately leave (and close) the whole component?

### ISSUE THREAD

**Issue by wmaurer** [NothingAG/adg-components#8]
The current implementation allows one to navigation between options of the dropdown using Tab/Shift-Tab and with arrow-up and arrow-down.
To exit the dropdown, one must press ESC.

Other multi-select components have a different behaviour, where when the dropdown is open, the arrow keys are used to move between options, but TAB will close the dropdown and move focus to the next focusable element (in this case the unselect all button)
As a committed keyboard user, I personally find this to be a more natural workflow.

A statement from @jmuheim is that he prefers not to override the focusing strategy of the browser. I can very-much sympathise with this goal.
However on the other hand, the fact that the component is backed by `input` fields rather than ARIA is simply an *implementation detail*. An ARIA-backed component could have the same UI but would come with no pre-determined behaviour. Therefore, my question is: 

**What is the preferred and most intuitive UX for keyboard users?**

**Comment by jmuheim** [comment]
I can very much sympathise with your preference. Admitted, I would also prefer it that way. But I'm a bit concerned that desktop screen reader users would be confused, because they don't really know (or care) that they are in a fancy dropdown element, they rather just perceive the standard HTML and probably expect to be able to reach those elements using `Tab`.

If we change this behaviour, at least we should provide an appropriate hint. I will ask some blind experts about their opinion. 🤔

**Comment by jmuheim** [comment]
For the records: at least keyboard users can press `Esc` to close the options, and then `Tab` will move the focus away from the component. Not exactly as you'd like it, Wayne, I know, but still quite a small price to pay.

**Comment by jmuheim** [comment]
Maybe we could show a little hint if a user presses `Tab` inside the options?

![CleanShot 2022-04-13 at 19 33 08@2x](https://user-images.githubusercontent.com/1814983/163237702-97626977-9337-488c-be35-f6033ceb5c9c.png)

**Comment by jmuheim** [comment]
Or we could indeed hijack the Tab key and just move focus out of the component and to the next element. While this could be a bit confusing to screen reader users, we could give them a (visually hidden) info about this behaviour, and then they would also simply need to use `Up`/`Down`, or any other special key like `X` (next checkbox).

I think they could live with that, if they need to. I'm unsure though whether the optimisation of one group's UX (keyboard-only users) should impede the UX of another group (screen reader users).

I'm also not sure how easy it is to detect the next focusable element on the page and set focus to it (we would have to manually do this, as we are overriding the browser standard behaviour). We could also just focus the "Open/close" button, but if we remove its "natural" focusability (#16), it might feel weird that it's suddenly focused now, even though it can't be focused otherwise.

**Comment by jmuheim** [comment]
As explained here (https://github.com/NothingAG/adg-components/issues/20#issuecomment-1112385245), GitHub also uses `Tab` to move between options inside their multi dropdown (ie. "Assigness", "Labels").

Let's keep it the way it is for now.
